### PR TITLE
Fixed episode_title defect

### PR DESCRIPTION
**Pull request by cxhamilton**
Fixed episode_title defect

### CODE REVIEW

**Comment by hugbug** [comment]
Thanks!

Multiple commits isn't a problem. All the changes will be merged as one commit.

Can you please restore formatting of testsort.py (in additional commit)?
Changing formatting of existing files is a bad thing making the tracking of changes hard.

**Comment by cxhamilton** [comment]
I will back out the reformatting, but leave in the change that I made. Otherwise, the first test after the DNZBHeader test will fail. That said, I urge you to consider reformatting or accepting a PR to reformat the file to be inline with [PEP8](https://www.python.org/dev/peps/pep-0008/) guidelines.

**Comment by cxhamilton** [comment]
Done.

**Comment by hugbug** [comment]
> I urge you to consider reformatting or accepting a PR to reformat the file to be inline with PEP8 guidelines.

Oh, I thought tabs were allowed :flushed:

Please submit  PR if you like. That's a small file anyway. I hope we don't have to reformat VideoSort.py?

**Pull request merged**
